#Replication controller object:
#This configuration file defines a ReplicationController named test-rc,
#which will maintain three replicas of a container based on the nginx:latest image.
#The selector field specifies that the controller should manage any pods with the label app: test-app.
#The template field defines the Pod template used by the controller, 
#which includes a single container named test-container running on port 80.

apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
spec:
  replicas: 3
  selector:
    app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-container
        image: nginx:latest
        ports:
        - containerPort: 80
